name: 酷狗音乐自动签到

on:
  workflow_dispatch: # 保留手动触发功能
  schedule:
    - cron: '1 16 * * *' # 北京时间 00:01 对应 UTC 时间 16:01

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
        env:
          NODEJS_ORG_MIRROR: https://npmmirror.com/mirrors/node

      - name: 安装依赖
        run: npm install

      - name: 运行签到脚本
        run: npm run main
        env:
          USERINFO: ${{ secrets.USERINFO }}
